apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/your-org/your-app-repo.git   # Git repository URL
    targetRevision: main                                    # Branch, tag, or commit hash
    path: test                                               # Relative path to the folder inside the repo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
