# 1. ConfigMap to store custom HTML with color changes
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-color-config
  namespace: argocd
  namespace: argocd
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Custom NGINX Page</title>
        <style>
            body {
                background-color: lightgreen; /* Background color */
                color: darkred;               /* Text color */
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 50px;
            }
        </style>
    </head>
    <body>
        <h1>Welcome to the Custom NGINX Page!</h1>
        <p>This page has a light green background and dark red text.</p>
    </body>
    </html>

---
# 2. NGINX Deployment that uses the ConfigMap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html-content
          configMap:
            name: nginx-color-config
            items:
              - key: index.html
                path: index.html

---
# 3. NGINX Service to expose the deployment
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NOdePort  # Change to NodePort if using a local cluster
